"""Auto-generate and run data-quality checks on the loaded data.

Writing DQ tests is the chore engineers skip, and data quality is where teams
lose the most time. So the tool profiles what actually landed and proposes
deterministic checks (row count, not-null on fully-populated columns, uniqueness
on candidate keys). These are plain SQL, so they are portable and can be
exported to a `data_quality.sql` file and run in CI or the warehouse later.

Optionally, if an LLM is configured, it can suggest a few domain-specific checks
on top — but the deterministic core needs no API key and always runs.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import duckdb

from .plan import INTERNAL_PREFIX


@dataclass
class Check:
    name: str
    table: str
    # SQL returning the number of BAD rows (0 == healthy).
    bad_count_sql: str


@dataclass
class CheckResult:
    check: Check
    bad_rows: int
    passed: bool


def _tables(con, schema: str) -> list[str]:
    rows = con.execute(
        "SELECT table_name FROM information_schema.tables "
        "WHERE table_schema = ? ORDER BY table_name",
        [schema],
    ).fetchall()
    return [r[0] for r in rows if not r[0].startswith(INTERNAL_PREFIX)]


def _columns(con, schema: str, table: str) -> list[str]:
    rows = con.execute(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_schema = ? AND table_name = ? ORDER BY ordinal_position",
        [schema, table],
    ).fetchall()
    return [r[0] for r in rows if not r[0].startswith(INTERNAL_PREFIX)]


def generate_checks(db_path: str | Path, schema: str = "sandbox") -> list[Check]:
    """Profile the data and derive deterministic quality checks."""
    con = duckdb.connect(str(db_path), read_only=True)
    checks: list[Check] = []
    try:
        catalog = con.execute("SELECT current_database()").fetchone()[0]
        for tbl in _tables(con, schema):
            fq = f'"{catalog}"."{schema}"."{tbl}"'
            total = con.execute(f"SELECT count(*) FROM {fq}").fetchone()[0]

            # 1) Table is not empty.
            checks.append(
                Check(
                    name=f"{tbl}: not empty",
                    table=tbl,
                    bad_count_sql=f"SELECT CASE WHEN count(*) = 0 THEN 1 ELSE 0 END FROM {fq}",
                )
            )
            if total == 0:
                continue

            for col in _columns(con, schema, tbl):
                qcol = f'"{col}"'
                nulls = con.execute(
                    f"SELECT count(*) FROM {fq} WHERE {qcol} IS NULL"
                ).fetchone()[0]
                distinct = con.execute(
                    f"SELECT count(DISTINCT {qcol}) FROM {fq}"
                ).fetchone()[0]

                # 2) Columns fully populated in the sample -> expect NOT NULL.
                if nulls == 0:
                    checks.append(
                        Check(
                            name=f"{tbl}.{col}: no nulls",
                            table=tbl,
                            bad_count_sql=f"SELECT count(*) FROM {fq} WHERE {qcol} IS NULL",
                        )
                    )

                # 3) Candidate key (distinct == rows, and more than one row) -> expect UNIQUE.
                if total > 1 and distinct == total:
                    checks.append(
                        Check(
                            name=f"{tbl}.{col}: unique",
                            table=tbl,
                            bad_count_sql=(
                                f"SELECT count(*) FROM (SELECT {qcol} FROM {fq} "
                                f"GROUP BY {qcol} HAVING count(*) > 1)"
                            ),
                        )
                    )
        return checks
    finally:
        con.close()


def run_checks(db_path: str | Path, checks: list[Check]) -> list[CheckResult]:
    con = duckdb.connect(str(db_path), read_only=True)
    try:
        results = []
        for chk in checks:
            bad = con.execute(chk.bad_count_sql).fetchone()[0]
            results.append(CheckResult(check=chk, bad_rows=int(bad), passed=int(bad) == 0))
        return results
    finally:
        con.close()


def checks_to_sql(checks: list[Check]) -> str:
    """Export checks as a runnable, self-documenting SQL file."""
    lines = [
        "-- Data-quality checks generated by nl2pipe.",
        "-- Each query should return 0. Non-zero = failing rows.",
        "",
    ]
    for chk in checks:
        lines.append(f"-- {chk.name}")
        lines.append(f"{chk.bad_count_sql.strip()};")
        lines.append("")
    return "\n".join(lines)


def suggest_llm_checks(db_path: str | Path, schema: str, model: str | None) -> list[Check]:
    """Optional: ask an LLM for domain-specific checks. Needs the 'llm' extra."""
    from . import llm
    from .prompts import DQ_PROMPT

    con = duckdb.connect(str(db_path), read_only=True)
    extra: list[Check] = []
    try:
        catalog = con.execute("SELECT current_database()").fetchone()[0]
        for tbl in _tables(con, schema):
            cols = con.execute(
                "SELECT column_name, data_type FROM information_schema.columns "
                "WHERE table_schema = ? AND table_name = ? ORDER BY ordinal_position",
                [schema, tbl],
            ).fetchall()
            payload = {"table": tbl, "columns": [{"name": c[0], "type": c[1]} for c in cols]}
            raw = llm.complete(DQ_PROMPT, json.dumps(payload), model=model)
            try:
                items = json.loads(raw.strip().removeprefix("```json").removeprefix("```").removesuffix("```"))
            except json.JSONDecodeError:
                continue
            for it in items:
                where = it.get("bad_rows_where")
                if not where:
                    continue
                extra.append(
                    Check(
                        name=f"{tbl}: {it.get('name', 'llm check')}",
                        table=tbl,
                        bad_count_sql=(
                            f'SELECT count(*) FROM "{catalog}"."{schema}"."{tbl}" WHERE {where}'
                        ),
                    )
                )
        return extra
    finally:
        con.close()
